flippy_article: 1
flippy_head_article: 0
flippy_show_empty_article: 0
flippy_prev_label_article: Previous
flippy_next_label_article: Next
flippy_first_last_article: 0
flippy_first_label_article: ''
flippy_last_labelarticle: ''
flippy_loop_article: 0
flippy_random_article: 0
flippy_random_label_article: ''
flippy_truncate_article: ''
flippy_ellipsearticle: ''
flippy_custom_sorting_article: 0
flippy_sort_article: created
flippy_order_article: ASC
